### ISSUE TITLE
Message.getErrorCode() does not parse JSON error_code number correctly

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-java#161] opened 2014-10-28 13:30 UTC
If you invoke `getErrorCode()`

https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/resource/instance/Message.java#L229

on a `Message` object that has it populated, you get this error:

```
java.lang.IllegalArgumentException: Property error_code is an object.  Use getObject() instead.
	at com.twilio.sdk.resource.InstanceResource.getProperty(InstanceResource.java:79)
	at com.twilio.sdk.resource.instance.Message.getErrorCode(Message.java:231)
```

because `getProperty(...)` only works for JSON string attributes.

**Comment by bonefishky** [comment] 2015-07-10 20:24
I see there has been no comment or movement on this issue.  We are currently experiencing, seeing this issues from time to time.  We catch it nicely and log that an error occurred but we have no way of understanding why or what the error is.  Clearly the JSON is in a different format than the getErrorCode expects as alexcchan has pointed out above.  Would be nice to have a clear work around or fix for this.  We are unable to reproduce exactly which error is causing the response package to be different.

**Comment by jingming** [comment] 2016-10-05 23:32
We have updated the library with better JSON parsing using Jackson. You should no longer see this error in version `7.0.0` and above.

**Closed by jingming** 2016-10-05 23:32 UTC
