### ISSUE TITLE
NoSuchMethodError: org.apache.http.impl.client.DefaultRedirectStrategy.<init>(java.lang.String[])

### ISSUE THREAD

**Issue by dipanshu91** [twilio/twilio-java#708] opened 2022-09-13 19:49 UTC
I'm getting _NoSuchMethodError: org.apache.http.impl.client.DefaultRedirectStrategy.<init>(java.lang.String[])_ exception with 
Twilio v9.0.0-rc.4. 
Spring Boot v2.5.6. 
Java v11. 

Not added any external dependency for httpclient. What should be fix for this?

**Comment by dipanshu91** [comment] 2022-09-13 19:50
@thinkingserious @childish-sambino : Can you please help with above?

**Comment by kridai** [comment] 2022-09-15 04:44
Hi @dipanshu91 , I did try reproducing the issue with the same configuration as you, but couldn't. This could be due to dependency conflict issue, since the httpclient version in [twilio sdk ](https://github.com/twilio/twilio-java/blob/9.0.0-rc/pom.xml#L221-L223) should have org.apache.http.impl.client.DefaultRedirectStrategy method. One way to find out the httpclient version is using the command `mvn dependency:tree -Dincludes=org.apache.httpcomponents:httpclient`

**Comment by blcakcatming** [comment] 2022-09-29 08:51
I update the `httpclient` dependency solved this problem
```
<!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient -->
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.13</version>
</dependency>
```

**Comment by childish-sambino** [comment] 2022-09-30 14:30
@dipanshu91 Does updating the `httpclient` dependency resolve the issue you're seeing?

**Comment by dipanshu91** [comment] 2022-09-30 14:40
After adding the httpclient dependency it got resolved. But the question was why we required to do that? Can't Twilio handle this conflict within SDK itself?

**Comment by childish-sambino** [comment] 2022-09-30 14:48
It depends on how the dependencies are being resolved in your application. Recommend using your build tool to inspect the dependency tree to determine where the potentially conflicting version of `httpclient` is being pulled from.

**Comment by rakatyal** [comment] 2022-10-31 18:03
Closing due to inactivity.

**Closed by rakatyal** 2022-10-31 18:03 UTC
Labels: type: question, status: waiting for feedback
